{
  "!type": "Form",
  "_uuid": "00eb4435a77a41c1aff606c11cf3be85",
  "HTML": "",
  "attributes": "",
  "background": "",
  "backgroundimage": "",
  "borderColor": "",
  "borderStyle": "",
  "borderWidth": "",
  "cached_js": "\n // url that Postman made with all the parameters embedded into it\nlet requestURL = \"https://maps.googleapis.com/maps/api/place/nearbysearch/json?key=AIzaSyBrdO0bwS9WnFcoOvwmtDRqaCjc7orrBAo&location=41.276900,-95.942310&rankby=distance&type=restaurant\"\n\n/*\nfunction addtoDB() {\n// add data to DB if you want to - just some sample code\n\n// need to add/use global database password, query, and results variables to project\n    query = \"whatever\"\n    req = Ajax(\"https://ormond.creighton.edu/courses/375/ajax-connection.php\", \"POST\", \"host=ormond.creighton.edu&user=clc90595&pass=\" + pw + \"&database=clc90595&query=\" + query)\n\n    if (req.status == 200) { //transit worked.\n        // code goes here to process data or check for 500 code\n    } else \n        // transit error\n        NSB.MsgBox(\"Network error: \" + req.status)\n}\n*/\n\nfunction onXHRLoad() {\n    let message = \"\"\n    let apiData = JSON.parse(this.responseText)\n    //for (i = 0; i <= apiData.results.length - 1; i++) {\n   for (i = 0; i <= 4; i++) {\n        console.log(`${apiData.results[i].name}`)\n        message = message + apiData.results[i].name + \"\\n\"\n    }\n    // change name of textArea below\n    txtaCloseRest.value = message\n    \n    // if want to add to database call a function here that does that\n    // addToDatabase()\n}\n\nfunction callAPI(URL) {\n    var xhttp = new XMLHttpRequest();\n    \n    // if you need cors (you'll get a cors error if you don't have it and you need it)\n    // use this code to add the cors code to your url \n        xhttp.open('GET', 'https://cors-anywhere.herokuapp.com/' + URL)\n    \n    // if you DON'T need cors use this code\n        //xhttp.open('GET',URL)\n    \n    // if you need to set the returned data type, use this line of code: \n        //xhttp.setRequestHeader('Content-Type', 'application/json')\n    \n    // if you need authorization token (stored in myToken) use this line of code: \n        // xhttp.setRequestHeader('Authorization', 'Bearer ' + myToken)\n    \n    // if you need a key and it's not in the url use code in one of the following\n    // examples (think of headers as parameters)\n    // or just use the Postman url which has all the parameters already added like I did here. \n    \n        \n        //xhttp.setRequestHeader('key','AIzaSyCE-pjULPU_Gp5Qf0qL39tVsdJBX55J0cY')\n        //xhttp.setRequestHeader('location','41.276900,-95.942310')\n        //xhttp.setRequestHeader('rankby','distance')\n        //xhttp.setRequestHeader('type','restaurant')\n        \n\n    // make the API request\n    xhttp.addEventListener('load', onXHRLoad)\n    xhttp.send()\n}\n\n\n\nbtnSeeRestaurants.onclick=function(){\n  callAPI(requestURL)\n}\n\nGoogleRestaurants.onshow=function(){\n  txtaCloseRest_contents.style.height = \"100px\"\n}\n\n",
  "cached_js_script_hash": "530a3740f28290e104d8446c48dc4083",
  "children": [
    {
      "!type": "Button_bs4",
      "_uuid": "58d3c584a6d346ad9a3eea486506cd51",
      "ChangeForm": "",
      "appearance": " btn-secondary",
      "backgroundColor": "",
      "badge": "",
      "badgeAppearance": " badge-info",
      "blockLevel": "",
      "borderColor": "",
      "borderStyle": "",
      "borderWidth": "",
      "bottom": "auto",
      "cached_js": "",
      "cached_js_script_hash": "d41d8cd98f00b204e9800998ecf8427e",
      "children": [],
      "class": "",
      "color": "",
      "disabled": "",
      "display": "",
      "expanded_pmp": true,
      "fontFamily": "",
      "fontSize": "",
      "fontStyle": "",
      "fontWeight": "",
      "groupStyle": "",
      "grouping": "",
      "height": "auto",
      "hidden": "",
      "icon": "",
      "iconTitle": "",
      "id": "btnSeeRestaurants",
      "left": 24,
      "mAll": "",
      "mBottom": "",
      "mLeft": "",
      "mRight": "",
      "mTop": "",
      "onclick": "btnSeeRestaurants.onclick()",
      "onmousedown": "",
      "onmousemove": "",
      "onmouseout": "",
      "onmouseup": "",
      "onresize": "",
      "ontouchend": "",
      "ontouchmove": "",
      "ontouchstart": "",
      "outline": "",
      "pAll": "",
      "pBottom": "",
      "pLeft": "",
      "pRight": "",
      "pTop": "",
      "popBody": "Body",
      "popClose": "hover",
      "popPosition": "",
      "popStyle": "popover",
      "popTitle": "Title",
      "right": "auto",
      "script": "",
      "size": " btn-md",
      "style": "",
      "toggleControl": "",
      "top": 56,
      "value": "See Restaurants by Harper",
      "width": "auto"
    },
    {
      "!type": "Textarea_bs4",
      "_uuid": "5652d50c904440d4aee8d391c5d922c9",
      "align": "",
      "autocapitalize": "",
      "autocomplete": "",
      "autocorrect": "",
      "backgroundColor": "",
      "badge": "",
      "badgeAppearance": " badge-info",
      "bottom": "auto",
      "cached_js": "",
      "cached_js_script_hash": "d41d8cd98f00b204e9800998ecf8427e",
      "children": [],
      "class": "",
      "color": "",
      "disabled": "",
      "display": "",
      "expanded_pmp": true,
      "fontFamily": "",
      "fontSize": "",
      "fontStyle": "",
      "fontWeight": "",
      "footer": "",
      "header": "Closest 5 restaurants",
      "headerCols": 4,
      "height": 256,
      "hidden": "",
      "icon": "",
      "iconTitle": "",
      "id": "txtaCloseRest",
      "inputmode": "",
      "left": 16,
      "mAll": "",
      "mBottom": "",
      "mLeft": "",
      "mRight": "",
      "mTop": "",
      "maxlength": "",
      "name": "",
      "onchange": "",
      "onclick": "",
      "oncopy": "",
      "oncut": "",
      "onfocusin": "",
      "onfocusout": "",
      "oninput": "",
      "onkeypress": "",
      "onkeyup": "",
      "onmousedown": "",
      "onmousemove": "",
      "onmouseout": "",
      "onmouseup": "",
      "onpaste": "",
      "onresize": "",
      "ontouchend": "",
      "ontouchmove": "",
      "ontouchstart": "",
      "pAll": "",
      "pBottom": "",
      "pLeft": "",
      "pRight": "",
      "pTop": "",
      "placeholder": "",
      "popBody": "Body",
      "popClose": "hover",
      "popPosition": "",
      "popStyle": "popover",
      "popTitle": "Title",
      "readonly": "readonly",
      "required": "",
      "right": "auto",
      "rows": "",
      "script": "",
      "spellcheck": "true",
      "style": "",
      "top": 128,
      "validation": "",
      "value": "",
      "valueCols": 8,
      "width": 288,
      "onfocus": ""
    }
  ],
  "class": "",
  "designHeight": 0,
  "designWidth": 0,
  "expanded_pmp": true,
  "fullScreen": "true",
  "height": 460,
  "id": "GoogleRestaurants",
  "language": "JavaScript",
  "left": "0",
  "locked": false,
  "modal": "false",
  "onhide": "",
  "onkeypress": "",
  "onresize": "",
  "onshow": "GoogleRestaurants.onshow()",
  "openMode": "none",
  "parentForm": "",
  "position": "absolute",
  "script": "\n // url that Postman made with all the parameters embedded into it\nlet requestURL = \"https://maps.googleapis.com/maps/api/place/nearbysearch/json?key=AIzaSyBrdO0bwS9WnFcoOvwmtDRqaCjc7orrBAo&location=41.276900,-95.942310&rankby=distance&type=restaurant\"\n\n/*\nfunction addtoDB() {\n// add data to DB if you want to - just some sample code\n\n// need to add/use global database password, query, and results variables to project\n    query = \"whatever\"\n    req = Ajax(\"https://ormond.creighton.edu/courses/375/ajax-connection.php\", \"POST\", \"host=ormond.creighton.edu&user=clc90595&pass=\" + pw + \"&database=clc90595&query=\" + query)\n\n    if (req.status == 200) { //transit worked.\n        // code goes here to process data or check for 500 code\n    } else \n        // transit error\n        NSB.MsgBox(\"Network error: \" + req.status)\n}\n*/\n\nfunction onXHRLoad() {\n    let message = \"\"\n    let apiData = JSON.parse(this.responseText)\n    //for (i = 0; i <= apiData.results.length - 1; i++) {\n   for (i = 0; i <= 4; i++) {\n        console.log(`${apiData.results[i].name}`)\n        message = message + apiData.results[i].name + \"\\n\"\n    }\n    // change name of textArea below\n    txtaCloseRest.value = message\n    \n    // if want to add to database call a function here that does that\n    // addToDatabase()\n}\n\nfunction callAPI(URL) {\n    var xhttp = new XMLHttpRequest();\n    \n    // if you need cors (you'll get a cors error if you don't have it and you need it)\n    // use this code to add the cors code to your url \n        xhttp.open('GET', 'https://cors-anywhere.herokuapp.com/' + URL)\n    \n    // if you DON'T need cors use this code\n        //xhttp.open('GET',URL)\n    \n    // if you need to set the returned data type, use this line of code: \n        //xhttp.setRequestHeader('Content-Type', 'application/json')\n    \n    // if you need authorization token (stored in myToken) use this line of code: \n        // xhttp.setRequestHeader('Authorization', 'Bearer ' + myToken)\n    \n    // if you need a key and it's not in the url use code in one of the following\n    // examples (think of headers as parameters)\n    // or just use the Postman url which has all the parameters already added like I did here. \n    \n        \n        //xhttp.setRequestHeader('key','AIzaSyCE-pjULPU_Gp5Qf0qL39tVsdJBX55J0cY')\n        //xhttp.setRequestHeader('location','41.276900,-95.942310')\n        //xhttp.setRequestHeader('rankby','distance')\n        //xhttp.setRequestHeader('type','restaurant')\n        \n\n    // make the API request\n    xhttp.addEventListener('load', onXHRLoad)\n    xhttp.send()\n}\n\n\n\nbtnSeeRestaurants.onclick=function(){\n  callAPI(requestURL)\n}\n\nGoogleRestaurants.onshow=function(){\n  txtaCloseRest_contents.style.height = \"100px\"\n}\n\n",
  "setFocusID": "",
  "style": "",
  "theme": "",
  "top": "0",
  "width": 320,
  "_functions": [
    {
      "!type": "Form",
      "_uuid": "e84d3568fb50450ab9e696b493b47abd",
      "cached_js": "",
      "cached_js_script_hash": "d41d8cd98f00b204e9800998ecf8427e",
      "children": [],
      "expanded_pmp": true,
      "id": "addtoDB",
      "location": [
        4,
        5
      ],
      "script": "",
      "signature": "function addtoDB() {"
    },
    {
      "!type": "Form",
      "_uuid": "0d9de7c31188468ea6ea45cc44e07909",
      "cached_js": "",
      "cached_js_script_hash": "d41d8cd98f00b204e9800998ecf8427e",
      "children": [],
      "expanded_pmp": true,
      "id": "onXHRLoad",
      "location": [
        18,
        19
      ],
      "script": "",
      "signature": "function onXHRLoad() {"
    },
    {
      "!type": "Form",
      "_uuid": "ded8ead1be8a4965af2afcf0f52d6379",
      "cached_js": "",
      "cached_js_script_hash": "d41d8cd98f00b204e9800998ecf8427e",
      "children": [],
      "expanded_pmp": true,
      "id": "callAPI",
      "location": [
        31,
        32
      ],
      "script": "",
      "signature": "function callAPI(requestURL) {"
    },
    {
      "!type": "Form",
      "_uuid": "e300369374dd44d0b146ac761f9f4b7f",
      "cached_js": "",
      "cached_js_script_hash": "d41d8cd98f00b204e9800998ecf8427e",
      "children": [],
      "expanded_pmp": true,
      "id": "btnSeeRestaurants.onclick",
      "location": [
        65,
        66
      ],
      "script": "",
      "signature": "btnSeeRestaurants.onclick()"
    },
    {
      "!type": "Form",
      "_uuid": "e517eb9a5eda498cada8b9b660c8103c",
      "cached_js": "",
      "cached_js_script_hash": "d41d8cd98f00b204e9800998ecf8427e",
      "children": [],
      "expanded_pmp": true,
      "id": "GoogleRestaurants.onshow",
      "location": [
        69,
        70
      ],
      "script": "",
      "signature": "GoogleRestaurants.onshow()"
    }
  ]
}